name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Frontend deploy
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2
         with:
           node-version: '20.11.1'
       - name: git pull
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             sudo bash
             cd ../..
             cd var/www/html/
             ls
             cd 2024_1_Refugio/
             git pull
       - name: npm restart
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             sudo bash
             cd ../..
             cd var/www/html/2024_1_Refugio/
             sudo apt update
             sudo apt install curl
             curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
             nvm install 20.11.1
             nvm use 20.11.1
             npm install -g npm@10.2.4
             npm ci
             npm run build:prod