name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  deploy:
    name: Frontend deploy
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
       - name: Setup Node.js environment
         uses: actions/setup-node@v2
         with:
           node-version: '20.11.1'
       - name: git pull
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: | 
             cd ../..
             cd var/www/html/2024_1_Refugio/
             sudo git pull
       - name: npm restart
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd ../..
             cd var/www/html/2024_1_Refugio/
             npm ci
             npm run build:prod